cache:
  directories:
    - .build/checkouts
    - .build/repositories
os: osx
language: swift
osx_image: xcode13.4
script:
  - swift build
deploy:
  provider: script
  script: pod trunk push
  on:
    tags: true
